In [7]:
# necessary import
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.datasets import fetch_covtype
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.model_selection import cross_val_score
from sklearn.tree import DecisionTreeClassifier

In [13]:

# load the iris dataset
iris = fetch_covtype()
dataset = pd.DataFrame(columns=iris.feature_names,data=iris.data)
dataset['target'] = iris.target
dataset



age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0      52    1   0       125   212    0        1      168      0      1.0   
1      53    1   0       140   203    1        0      155      1      3.1   
2      70    1   0       145   174    0        1      125      1      2.6   
3      61    1   0       148   203    0        1      161      0      0.0   
4      62    0   0       138   294    1        1      106      0      1.9   
...   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
1020   59    1   1       140   221    0        1      164      1      0.0   
1021   60    1   0       125   258    0        0      141      1      2.8   
1022   47    1   0       110   275    0        0      118      1      1.0   
1023   50    0   0       110   254    0        0      159      0      0.0   
1024   54    1   0       120   188    0        1      113      0      1.4   

      slope  ca  thal  target  
0         2   2     3       0  
1         0   0     3       0  
2         0   0     3       0  
3         2   1     3       0  
4         1   3     2       0  
...     ...  ..   ...     ...  
1020      2   0     2       1  
1021      1   1     3       0  
1022      1   1     2       0  
1023      2   0     2       1  
1024      1   1     3       0  

[1025 rows x 14 columns]

In [3]:
# divide the dataset into class and target variable
X = dataset.iloc[:, 0:53].values
y = dataset.iloc[:, 54].values

# Preprocess the dataset and divide into train and test
sc = StandardScaler()
X = sc.fit_transform(X)
le = LabelEncoder()
y = le.fit_transform(y)
X_train, X_test,y_train, y_test = train_test_split(X, y,test_size=0.2)


# apply Linear Discriminant Analysis
lda = LinearDiscriminantAnalysis(n_components=6)
X_train = lda.fit_transform(X_train, y_train)
X_test = lda.transform(X_test)

"""
# plot the scatterplot
plt.scatter(
    X_train[:, 0], X_train[:, 1],
    c=y_train,
    cmap='rainbow',
    alpha=0.7, edgecolors='b'
)
"""



"\n# plot the scatterplot\nplt.scatter(\n    X_train[:, 0], X_train[:, 1],\n    c=y_train,\n    cmap='rainbow',\n    alpha=0.7, edgecolors='b'\n)\n"

In [4]:
# classify using random forest classifier
classifier = RandomForestClassifier(max_depth=2,
                                    random_state=0)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)

# print the accuracy and confusion matrix
print('Accuracy : ' + str(accuracy_score(y_test, y_pred)))
conf_m = confusion_matrix(y_test, y_pred)
print(conf_m)

Accuracy : 0.6806106554908221
[[31145 11085    16     0     0     0     0]
 [11847 44207   878     0     0     0     0]
 [ 1466  1988  3737     0     0     0     0]
 [  361   149    57     0     0     0     0]
 [    2  1792    51     0     0     0     0]
 [  537  1511  1330     0     0     0     0]
 [ 4028    16     0     0     0     0     0]]


In [5]:

from sklearn.neighbors import KNeighborsClassifier
neigh = KNeighborsClassifier(n_neighbors=4)
neigh.fit(X_train, y_train)
y_pred = neigh.predict(X_test)
# print the accuracy and confusion matrix
print('Accuracy : ' + str(accuracy_score(y_test, y_pred)))
conf_m = confusion_matrix(y_test, y_pred)
print(conf_m)


Accuracy : 0.8872404326910664
[[38872  3089     2     0    46    11   226]
 [ 5938 50443   167     1   187   174    22]
 [    5   320  6438    40    12   376     0]
 [    0     2   155   371     0    39     0]
 [   62   566    35     0  1179     3     0]
 [   17   307   734    25     7  2288     0]
 [  477    58     0     0     0     0  3509]]


In [11]:
from sklearn import tree 
clf = DecisionTreeClassifier(random_state=42)
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
# print the accuracy and confusion matrix
print('Accuracy : ' + str(accuracy_score(y_test, y_pred)))
conf_m = confusion_matrix(y_test, y_pred)
print(conf_m)


Accuracy : 0.8228358992452862
[[34391  7102    12     0    95    30   616]
 [ 7380 48158   335     1   618   355    85]
 [   13   372  5930   105    31   740     0]
 [    0     0   145   381     0    41     0]
 [   80   595    30     0  1123    16     1]
 [   27   330   725    46    15  2235     0]
 [  578    68     0     0     0     0  3398]]


In [13]:
from sklearn.ensemble  import RandomForestClassifier 
clf = RandomForestClassifier(random_state=42)
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
# print the accuracy and confusion matrix
print('Accuracy : ' + str(accuracy_score(y_test, y_pred)))
conf_m = confusion_matrix(y_test, y_pred)
print(conf_m)

Accuracy : 0.8852267153171605
[[36638  5324     8     0    26    13   237]
 [ 3977 52338   232     1   128   223    33]
 [    3   273  6454    35     8   418     0]
 [    0     1   143   386     0    37     0]
 [   48   657    26     0  1106     8     0]
 [   14   257   661    19     4  2423     0]
 [  486    37     0     0     0     0  3521]]


In [7]:
import numpy as np

from sklearn.naive_bayes import GaussianNB
clf = GaussianNB()
clf.fit(X_train, y_train)
y_pred= clf.predict(X_test)
print('Accuracy : ' + str(accuracy_score(y_test, y_pred)))
conf_m = confusion_matrix(y_test, y_pred)
print(conf_m)

Accuracy : 0.6516354999440634
[[31534  6218    28     0    49   237  4180]
 [19220 33640  1667    20   157  1935   293]
 [    0   281  6248   335    49   278     0]
 [    0     0   244   323     0     0     0]
 [   96  1364   143     0   142   100     0]
 [    0   429  2104    93   116   636     0]
 [  782    43    16     0     0     4  3199]]
