In [10]:
# necessary import
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.datasets import fetch_covtype
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.metrics import accuracy_score, confusion_matrix,f1_score
from sklearn.model_selection import cross_val_score
from sklearn.tree import DecisionTreeClassifier

In [13]:
cov_type = fetch_covtype()
dataset = pd.DataFrame(columns=cov_type.feature_names,data=cov_type.data)
dataset['target'] = cov_type.target
dataset



Elevation  Aspect  Slope  Horizontal_Distance_To_Hydrology  \
0          2596.0    51.0    3.0                             258.0   
1          2590.0    56.0    2.0                             212.0   
2          2804.0   139.0    9.0                             268.0   
3          2785.0   155.0   18.0                             242.0   
4          2595.0    45.0    2.0                             153.0   
...           ...     ...    ...                               ...   
581007     2396.0   153.0   20.0                              85.0   
581008     2391.0   152.0   19.0                              67.0   
581009     2386.0   159.0   17.0                              60.0   
581010     2384.0   170.0   15.0                              60.0   
581011     2383.0   165.0   13.0                              60.0   

        Vertical_Distance_To_Hydrology  Horizontal_Distance_To_Roadways  \
0                                  0.0                            510.0   
1                                 -6.0                            390.0   
2                                 65.0                           3180.0   
3                                118.0                           3090.0   
4                                 -1.0                            391.0   
...                                ...                              ...   
581007                            17.0                            108.0   
581008                            12.0                             95.0   
581009                             7.0                             90.0   
581010                             5.0                             90.0   
581011                             4.0                             67.0   

        Hillshade_9am  Hillshade_Noon  Hillshade_3pm  \
0               221.0           232.0          148.0   
1               220.0           235.0          151.0   
2               234.0           238.0          135.0   
3               238.0           238.0          122.0   
4               220.0           234.0          150.0   
...               ...             ...            ...   
581007          240.0           237.0          118.0   
581008          240.0           237.0          119.0   
581009          236.0           241.0          130.0   
581010          230.0           245.0          143.0   
581011          231.0           244.0          141.0   

        Horizontal_Distance_To_Fire_Points  ...  Soil_Type_31  Soil_Type_32  \
0                                   6279.0  ...           0.0           0.0   
1                                   6225.0  ...           0.0           0.0   
2                                   6121.0  ...           0.0           0.0   
3                                   6211.0  ...           0.0           0.0   
4                                   6172.0  ...           0.0           0.0   
...                                    ...  ...           ...           ...   
581007                               837.0  ...           0.0           0.0   
581008                               845.0  ...           0.0           0.0   
581009                               854.0  ...           0.0           0.0   
581010                               864.0  ...           0.0           0.0   
581011                               875.0  ...           0.0           0.0   

        Soil_Type_33  Soil_Type_34  Soil_Type_35  Soil_Type_36  Soil_Type_37  \
0                0.0           0.0           0.0           0.0           0.0   
1                0.0           0.0           0.0           0.0           0.0   
2                0.0           0.0           0.0           0.0           0.0   
3                0.0           0.0           0.0           0.0           0.0   
4                0.0           0.0           0.0           0.0           0.0   
...              ...           ...           ...           ...           ...   
581007           0.0           0.0           0.0           0.0           0.0   
5810

In [14]:
# divide the dataset into class and target variable
X = dataset.iloc[:, 0:53].values
y = dataset.iloc[:, 54].values

# Preprocess the dataset and divide into train and test
sc = StandardScaler()
X = sc.fit_transform(X)
le = LabelEncoder()
y = le.fit_transform(y)
X_train, X_test,y_train, y_test = train_test_split(X, y,test_size=0.2)






In [22]:
# apply Linear Discriminant Analysis
lda = LinearDiscriminantAnalysis(n_components=6)
X_train = lda.fit_transform(X_train, y_train)
X_test = lda.transform(X_test)


In [23]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB

classifiers = [RandomForestClassifier(max_depth=2,random_state=0),
               KNeighborsClassifier(n_neighbors=4),
               DecisionTreeClassifier(random_state=42),
               GaussianNB()]
classifiers_names = ["RandomForestClassifier",
               "KNeighborsClassifier",
               "DecisionTreeClassifier",
               "GaussianNB"]
classifiers_scores = []



for index,classifier in enumerate(classifiers):
   
    classifier.fit(X_train, y_train)
    y_pred = classifier.predict(X_test)
    
    accuracy_score_v = accuracy_score(y_test, y_pred)
    f1_score_v = f1_score(y_test, y_pred,average="weighted")
    # print the accuracy and confusion matrix
    print(f"        {classifiers_names[index]}")
    print('Accuracy : ' + str(accuracy_score_v))
    print('F1 score : ' + str(f1_score_v))
    conf_m = confusion_matrix(y_test, y_pred)
    print(conf_m)
    print("-------------------------------------------------")


classifiers_scores.sort()


        RandomForestClassifier
Accuracy : 0.6777277695068114
F1 score : 0.6465435804960292
[[31232 11153    23     0     0     0     0]
 [11942 44059   735     0     0     0     0]
 [ 1474  2186  3463     0     0     0     0]
 [  322   137    36     0     0     0     0]
 [   18  1809    65     0     0     0     0]
 [  511  1654  1321     0     0     0     0]
 [ 4046    17     0     0     0     0     0]]
-------------------------------------------------
        KNeighborsClassifier
Accuracy : 0.8882472913780195
F1 score : 0.8877470485466044
[[39005  3157     2     0    38    10   196]
 [ 5896 50319   164     0   189   148    20]
 [    7   308  6401    49    16   342     0]
 [    0     0   132   329     0    34     0]
 [   70   569    28     0  1221     4     0]
 [   17   309   704    31     9  2416     0]
 [  480    57     0     0     0     0  3526]]
-------------------------------------------------
        DecisionTreeClassifier
Accuracy : 0.8229821949519376
F1 score : 0.82301197133822

In [19]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB

classifiers = [RandomForestClassifier(max_depth=2,random_state=0),
               KNeighborsClassifier(n_neighbors=4),
               DecisionTreeClassifier(random_state=42),
               GaussianNB()]
classifiers_names = ["RandomForestClassifier",
               "KNeighborsClassifier",
               "DecisionTreeClassifier",
               "GaussianNB"]
classifiers_scores = []



for index,classifier in enumerate(classifiers):
   
    classifier.fit(X_train, y_train)
    y_pred = classifier.predict(X_test)
    
    accuracy_score_v = accuracy_score(y_test, y_pred)
    f1_score_v = f1_score(y_test, y_pred,average="weighted")
    # print the accuracy and confusion matrix
    print(f"        {classifiers_names[index]}")
    print('Accuracy : ' + str(accuracy_score_v))
    print('F1 score : ' + str(f1_score_v))
    conf_m = confusion_matrix(y_test, y_pred)
    print(conf_m)
    print("-------------------------------------------------")


classifiers_scores.sort()


        RandomForestClassifier
Accuracy : 0.5843308692546664
F1 score : 0.5157087969569971
[[12772 29636     0     0     0     0     0]
 [ 2843 53790   103     0     0     0     0]
 [    0  5784  1339     0     0     0     0]
 [    0   488     7     0     0     0     0]
 [    0  1892     0     0     0     0     0]
 [    0  2941   545     0     0     0     0]
 [ 2542  1521     0     0     0     0     0]]
-------------------------------------------------
        KNeighborsClassifier
Accuracy : 0.9273512732029293
F1 score : 0.9270334408287298
[[40353  1867     2     0    41     2   143]
 [ 3650 52677   121     1   147   121    19]
 [    7   242  6584    42    15   233     0]
 [    0     1   105   362     0    27     0]
 [   63   396    36     0  1391     6     0]
 [   11   214   533    35     4  2689     0]
 [  310    47     0     0     1     0  3705]]
-------------------------------------------------
        DecisionTreeClassifier
Accuracy : 0.9399671264941525
F1 score : 0.93996818845313